### ISSUE TITLE
Fix call HttpException method - add statusCode

### ISSUE THREAD

**Issue by thieuquocnghi** [umbalaconmeogia/yii2-ssosubdomain#1]
yii\base\InvalidArgumentException: The HTTP status code is invalid
In Class ServiceProviderLoginAction:
>>
`throw new HttpException('You do not have permission to access this page');`

Fix like:
>>
throw new HttpException(403, 'You do not have permission to access this page');

**Comment by umbalaconmeogia** [comment]
Can you make a pull request for this?

**Comment by umbalaconmeogia** [comment]
The code is updated (pulled).
